### ISSUE TITLE
What is the best practice when dealing with large arguments

### ISSUE THREAD

**Issue by mbkupfer** [ubershmekel/filecache#11]
I'm trying to cache a function that takes in arguments that create huge keys.

Function:
`def merge(main_df, to_merge, year)`

`main_df` and `to_merge` are both pandas dataframes that are 75MB+ in size. Would there be a way to instead cache just the `__repl__` instead? Otherwise, is there a best practice here?

**Comment by ubershmekel** [comment]
Sounds like a unique use-case. Perhaps there's a version ID you could use instead of the full pandas dataframe as an argument?

**Comment by mbkupfer** [comment]
@ubershmekel is it possible to give custom key though? For instance it could be a keyword argument to the decorator.

Flask-caching does this via make_cache_key: 

make_cache_key – Default None. If set to a callable object, it will be called to generate the cache key
https://flask-caching.readthedocs.io/en/latest/api.html#cache-api

**Comment by ubershmekel** [comment]
```
def merge(main_df, to_merge, year):
    return merge_cache_key(make_your_own_key(main_df_repl), to_merge, year):
    
@filecache
def merge_cache_key(main_df_but_repled, to_merge, year):
    pass
```

Would that work?

**Comment by mbkupfer** [comment]
> ```
> def merge(main_df, to_merge, year):
>     return merge_cache_key(make_your_own_key(main_df_repl), to_merge, year):
>     
> @filecache
> def merge_cache_key(main_df_but_repled, to_merge, year):
>     pass
> ```
> 
> Would that work?

I gave it some thought and I don't think so as `merge` is a pandas `pipe` function. That means that I need to work on the actual dataframe that gets piped in and I wouldn't know how to proxy that by using a repl.

That said, the `year` parameter is always unique for each merge. If I can have the cache key just be the year then it would work. Could you add a feature where you can overwrite the automatically generated cache key, or specify to ignore specified parameters?

**Comment by JulianWgs** [comment]
Since you want to cache the result to disk anyway why not write the dataframe to disk as a parquet file? Parquet is really fast  :) Then both arguments will be the filename (which you could also versioned). 75MB of in-memory data will be considerably less when saved with parquet.

https://parquet.apache.org/
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_parquet.html

**Comment by mbkupfer** [comment]
Yes, I know and use parquet, but didn't think about using a filename as a parameter! Very crafty! Thanks @JulianWgs
