### ISSUE TITLE
Crashes with datetime as argument

### ISSUE THREAD

**Issue by purew** [ubershmekel/filecache#5]
> ? python -V
> Python 3.4.3
> ? pip list | grep filecache
> filecache (0.77)

```
from datetime import datetime
from filecache import filecache

@filecache(100)
def test(a,dt):
        return a + dt.timestamp()

print(test(10, datetime.utcnow()))
```

results in 

> python /tmp/test_filecache.py
> Traceback (most recent call last):
>   File "/tmp/test_filecache.py", line 9, in <module>
>     print(test(10, datetime.utcnow()))
>   File "/home/user/python/lib/python3.4/site-packages/filecache/**init**.py", line 132, in function_with_cache
>     key = _args_key(function, args, kwargs)
>   File "/home/user/python/lib/python3.4/site-packages/filecache/__init__.py", line 119, in _args_key
>     arguments_pickle = _pickle.dumps(arguments, protocol=0).decode('ascii')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 52: ordinal not in range(128)

**Comment by ubershmekel** [comment]
Thank you @PureW for reporting!

This has been fixed by the recent https://github.com/ubershmekel/filecache/pull/6

But I still added a test for datetime just in case at https://github.com/ubershmekel/filecache/commit/58bd8dd3c1acfea598fec7015bbce731a0db0515
